In [2]:
import yfinance as yf
import pandas as pd

pltr = yf.Ticker("PLTR")

expiries = pltr.options

print("Number of expiries:", len(expiries))
print(expiries)

Number of expiries: 19
('2026-10-16', '2026-10-23', '2026-10-30', '2026-11-06', '2026-11-13', '2026-11-20', '2026-12-18', '2027-01-15', '2027-02-19', '2027-03-19', '2027-04-16', '2027-05-21', '2027-06-17', '2027-09-17', '2027-12-17', '2028-01-21', '2028-06-16', '2028-12-15', '2029-01-19')

In [3]:
expiry = "2027-01-15"
chain = pltr.option_chain(expiry)
calls = chain.calls
puts = chain.puts

print("Calls shape:", calls.shape)
print("Puts shape:", puts.shape)

display(calls.head())
display(puts.head())

Calls shape: (73, 14)
Puts shape: (73, 14)

,contractSymbol,lastTradeDate,strike,lastPrice,bid,ask,change,percentChange,volume,openInterest,impliedVolatility,inTheMoney,contractSize,currency
0,PLTR270115C00020000,2026-10-08 14:00:19+00:00,20.0,181.30,187.45,190.80,0.000000,0.000000,1,1862,1.734376,True,REGULAR,USD
1,PLTR270115C00023000,2026-10-08 18:40:49+00:00,23.0,174.90,184.50,187.80,0.000000,0.000000,10,459,1.679689,True,REGULAR,USD
2,PLTR270115C00025000,2026-09-21 19:00:38+00:00,25.0,157.91,182.50,185.80,0.000000,0.000000,1,1692,1.613283,True,REGULAR,USD
3,PLTR270115C00028000,2026-10-08 14:32:07+00:00,28.0,172.25,179.55,182.75,0.000000,0.000000,1,153,1.525393,True,REGULAR,USD
4,PLTR270115C00030000,2026-10-09 19:40:56+00:00,30.0,178.37,178.05,180.75,15.549988,9.550416,2,1266,1.727540,True,REGULAR,USD

,contractSymbol,lastTradeDate,strike,lastPrice,bid,ask,change,percentChange,volume,openInterest,impliedVolatility,inTheMoney,contractSize,currency
0,PLTR270115P00020000,2026-10-09 15:27:32+00:00,20.0,0.02,0.00,0.03,0.01,100.0,160,12772,1.484378,False,REGULAR,USD
1,PLTR270115P00023000,2026-10-09 14:10:58+00:00,23.0,0.03,0.00,0.05,0.01,50.0,5,678,1.460940,False,REGULAR,USD
2,PLTR270115P00025000,2026-10-09 19:14:35+00:00,25.0,0.01,0.00,0.02,-0.01,-50.0,4,7347,1.296879,False,REGULAR,USD
3,PLTR270115P00028000,2026-10-09 13:39:03+00:00,28.0,0.03,0.01,0.05,0.01,50.0,10,1613,1.351566,False,REGULAR,USD
4,PLTR270115P00030000,2026-10-09 19:02:22+00:00,30.0,0.07,0.02,0.05,0.05,250.0,2,23512,1.320316,False,REGULAR,USD

In [4]:
valid_calls = calls[
    (calls["bid"]>0) &
    (calls["ask"]>0) &
    (calls["ask"] >= calls["bid"])
]

print("Valid calls:", len(valid_calls))
display(valid_calls[["strike", "bid", "ask"]])

Valid calls: 73

    strike     bid     ask
0     20.0  187.45  190.80
1     23.0  184.50  187.80
2     25.0  182.50  185.80
3     28.0  179.55  182.75
4     30.0  178.05  180.75
..     ...     ...     ...
68   370.0    0.48    0.58
69   380.0    0.33    0.52
70   390.0    0.25    0.51
71   400.0    0.22    0.46
72   410.0    0.13    0.22

[73 rows x 3 columns]

In [5]:
from datetime import datetime, timezone

snapshot_time = datetime.now(timezone.utc)

calls.to_csv("PLTR_calls_2027-01-15.csv", index=False)
puts.to_csv("PLTR_puts_2027-01-15.csv", index=False)

print("Snapshot UTC:", snapshot_time.isoformat())

Snapshot UTC: 2026-10-10T10:37:56.535997+00:00

In [6]:
import yfinance as yf
import pandas as pd
import numpy as np
from datetime import datetime, timezone

pltr = yf.Ticker("PLTR")

spot_data = pltr.history(period = "1d", interval = "1m")
print(spot_data.tail())
s0 = spot_data["Close"].iloc[-1]
print("Spot price: ", s0)

                                 Open        High         Low       Close  \
Datetime
2026-10-09 15:55:00-04:00  209.179993  209.309998  208.839996  208.880005
2026-10-09 15:56:00-04:00  208.869995  208.949997  208.639999  208.735001
2026-10-09 15:57:00-04:00  208.740005  208.899994  208.669998  208.887604
2026-10-09 15:58:00-04:00  208.899994  208.910004  208.770004  208.789993
2026-10-09 15:59:00-04:00  208.789993  209.160004  208.755005  209.065002

                           Volume  Dividends  Stock Splits
Datetime
2026-10-09 15:55:00-04:00  308236        0.0           0.0
2026-10-09 15:56:00-04:00  201896        0.0           0.0
2026-10-09 15:57:00-04:00  269549        0.0           0.0
2026-10-09 15:58:00-04:00  285504        0.0           0.0
2026-10-09 15:59:00-04:00  573654        0.0           0.0
Spot price:  209.06500244140625

In [7]:
import numpy as np
expiries_to_check = [
    "2026-11-20",
    "2026-12-18",
    "2027-01-15",
    "2027-02-19"
]
available_expiries = set(pltr.options)

for expiry in expiries_to_check:
    if expiry not in available_expiries:
        print(expiry, "Not available")
        continue
    chain = pltr.option_chain(expiry)
    calls = chain.calls
    puts =  chain.puts

    vaild_calls = calls[
        (calls["bid"]>0) &
        (calls["ask"]>0) &
        (calls["ask"] >= calls["bid"])    
    ]

    vaild_puts = puts[
        (puts["bid"]>0) &
        (puts["ask"]>0) &
        (puts["ask"] >= puts["bid"])
    ]

    print(
        expiry,
        "Valid call: ", len(vaild_calls),
        "Valid puts: ", len(vaild_puts)
    )

strike_lower_than_spot = calls[
        (calls["bid"]>0) &
        (calls["ask"]>0) &
        (calls["ask"] >= calls["bid"]) &
        (calls["strike"] < s0)    
    ]
print(len(strike_lower_than_spot))

strike_higher_than_spot = calls[
        (calls["bid"]>0) &
        (calls["ask"]>0) &
        (calls["ask"] >= calls["bid"]) &
        (calls["strike"] > s0)    
    ]
print(len(strike_higher_than_spot))

distance_to_spot = calls["strike"]-s0
strike_closest_to_spot = np.abs(distance_to_spot).idxmin()
atm_strike = calls.loc[strike_closest_to_spot, "strike"]
print(atm_strike)

2026-11-20 Valid call:  57 Valid puts:  50
2026-12-18 Valid call:  76 Valid puts:  59
2027-01-15 Valid call:  73 Valid puts:  62
2027-02-19 Valid call:  40 Valid puts:  40
28
12
210.0

In [8]:
expiry = "2027-01-15"

chain = pltr.option_chain(expiry)
calls = chain.calls

print(calls[["strike", "bid", "ask"]].head(15))

print("Positive bids:", (calls["bid"] > 0).sum())
print("Positive asks:", (calls["ask"] > 0).sum())

print("Missing bids:", calls["bid"].isna().sum())
print("Missing asks:", calls["ask"].isna().sum())

    strike     bid     ask
0     20.0  187.45  190.80
1     23.0  184.50  187.80
2     25.0  182.50  185.80
3     28.0  179.55  182.75
4     30.0  178.05  180.75
5     33.0  175.05  177.95
6     35.0  173.20  175.90
7     37.0  171.25  174.00
8     40.0  168.30  170.90
9     42.0  166.20  169.05
10    45.0  163.30  166.00
11    47.0  161.30  164.15
12    50.0  158.40  161.20
13    55.0  153.55  155.90
14    57.5  150.95  153.70
Positive bids: 73
Positive asks: 73
Missing bids: 0
Missing asks: 0

In [9]:
import pandas as pd
import numpy as np

calls = pd.read_csv("PLTR_calls_2027-01-15.csv")
puts = pd.read_csv("PLTR_puts_2027-01-15.csv")

print("Calls:", calls.shape)
print("Puts:", puts.shape)

display(calls.head())
display(puts.head())

Calls: (73, 14)
Puts: (73, 14)

,contractSymbol,lastTradeDate,strike,lastPrice,bid,ask,change,percentChange,volume,openInterest,impliedVolatility,inTheMoney,contractSize,currency
0,PLTR270115C00020000,2026-10-08 14:00:19+00:00,20.0,181.30,187.45,190.80,0.000000,0.000000,1,1862,1.734376,True,REGULAR,USD
1,PLTR270115C00023000,2026-10-08 18:40:49+00:00,23.0,174.90,184.50,187.80,0.000000,0.000000,10,459,1.679689,True,REGULAR,USD
2,PLTR270115C00025000,2026-09-21 19:00:38+00:00,25.0,157.91,182.50,185.80,0.000000,0.000000,1,1692,1.613283,True,REGULAR,USD
3,PLTR270115C00028000,2026-10-08 14:32:07+00:00,28.0,172.25,179.55,182.75,0.000000,0.000000,1,153,1.525393,True,REGULAR,USD
4,PLTR270115C00030000,2026-10-09 19:40:56+00:00,30.0,178.37,178.05,180.75,15.549988,9.550416,2,1266,1.727540,True,REGULAR,USD

,contractSymbol,lastTradeDate,strike,lastPrice,bid,ask,change,percentChange,volume,openInterest,impliedVolatility,inTheMoney,contractSize,currency
0,PLTR270115P00020000,2026-10-09 15:27:32+00:00,20.0,0.02,0.00,0.03,0.01,100.0,160,12772,1.484378,False,REGULAR,USD
1,PLTR270115P00023000,2026-10-09 14:10:58+00:00,23.0,0.03,0.00,0.05,0.01,50.0,5,678,1.460940,False,REGULAR,USD
2,PLTR270115P00025000,2026-10-09 19:14:35+00:00,25.0,0.01,0.00,0.02,-0.01,-50.0,4,7347,1.296879,False,REGULAR,USD
3,PLTR270115P00028000,2026-10-09 13:39:03+00:00,28.0,0.03,0.01,0.05,0.01,50.0,10,1613,1.351566,False,REGULAR,USD
4,PLTR270115P00030000,2026-10-09 19:02:22+00:00,30.0,0.07,0.02,0.05,0.05,250.0,2,23512,1.320316,False,REGULAR,USD

In [10]:
for name, df in [("Calls", calls), ("Puts", puts)]:
    valid = (
        (df["bid"] > 0)
        & (df["ask"] > 0)
        & (df["ask"] >= df["bid"])
    )

    print(name)
    print("Total contracts:", len(df))
    print("Valid quotes:", valid.sum())
    print("Valid quote ratio:", valid.mean())

Calls
Total contracts: 73
Valid quotes: 73
Valid quote ratio: 1.0
Puts
Total contracts: 73
Valid quotes: 62
Valid quote ratio: 0.8493150684931506

In [11]:
s0 = 198.72

for df in [calls, puts]:

    df["mid"] = (df["bid"] + df["ask"]) / 2

    df["spread"] = df["ask"] - df["bid"]

    df["relative_spread"] = (
        df["spread"] / df["mid"].replace(0, np.nan)
    )

    df["moneyness"] = s0 / df["strike"]

atm_calls = calls[
    (calls["strike"] >= 180)
    & (calls["strike"] <= 220)
]

atm_puts = puts[
    (puts["strike"] >= 180)
    & (puts["strike"] <= 220)
]

columns = [
    "strike", "bid", "ask", "mid",
    "relative_spread", "volume",
    "openInterest", "impliedVolatility"
]

display(atm_calls[columns])
display(atm_puts[columns])

,strike,bid,ask,mid,relative_spread,volume,openInterest,impliedVolatility
47,180.0,39.50,40.00,39.750,0.012579,231,7789,0.556828
48,185.0,35.55,36.50,36.025,0.026371,135,4551,0.540898
49,190.0,32.50,33.35,32.925,0.025816,908,7129,0.538030
50,195.0,29.55,30.45,30.000,0.030000,274,3755,0.535191
51,200.0,27.10,27.50,27.300,0.014652,1213,18478,0.533574
52,210.0,22.00,22.35,22.175,0.015784,707,14296,0.524419
53,220.0,17.75,18.20,17.975,0.025035,597,8959,0.521123

,strike,bid,ask,mid,relative_spread,volume,openInterest,impliedVolatility
47,180.0,8.40,8.75,8.575,0.040816,124,6440,0.499974
48,185.0,9.85,10.30,10.075,0.044665,307,2127,0.494909
49,190.0,11.75,12.15,11.950,0.033473,189,3984,0.493108
50,195.0,13.40,14.00,13.700,0.043796,198,2234,0.486516
51,200.0,15.75,16.20,15.975,0.028169,1645,2550,0.484075
52,210.0,20.60,21.25,20.925,0.031063,414,733,0.480901
53,220.0,26.20,27.00,26.600,0.030075,28,571,0.476629

In [12]:
atm_call = calls.loc[calls["strike"] == 200].iloc[0]
atm_put = puts.loc[puts["strike"] == 200].iloc[0]

print("Call last trade:", atm_call["lastTradeDate"])
print("Put last trade:", atm_put["lastTradeDate"])

print("Call IV:", atm_call["impliedVolatility"])
print("Put IV:", atm_put["impliedVolatility"])

print("Call Mid:", atm_call["mid"])
print("Put Mid:", atm_put["mid"])

Call last trade: 2026-10-09 19:59:57+00:00
Put last trade: 2026-10-09 19:59:12+00:00
Call IV: 0.5335740002441407
Put IV: 0.4840749835205078
Call Mid: 27.3
Put Mid: 15.975

In [13]:
snapshot_metadata = {
    "ticker": "PLTR",
    "expiration": "2027-01-15",
    "source": "Yahoo Finance via yfinance",
    "spot_reference": 198.72,
    "spot_reference_date": "2026-10-08",
    "option_quote_timestamp": "Unknown",
    "calls_count": len(calls),
    "puts_count": len(puts),
}

metadata = pd.Series(snapshot_metadata)
metadata.to_json(
    "../Data/PLTR_snapshot_metadata.json",
    indent=4
)

In [14]:
print(calls["contractSymbol"].head())
print(calls["strike"].nunique())
print(calls["lastTradeDate"].max())

0    PLTR270115C00020000
1    PLTR270115C00023000
2    PLTR270115C00025000
3    PLTR270115C00028000
4    PLTR270115C00030000
Name: contractSymbol, dtype: str
73
2026-10-09 19:59:57+00:00

In [15]:
from pathlib import Path

data_dir = Path("../Data")
data_dir.mkdir(parents=True, exist_ok=True)

for expiry in expiries_to_check:
    chain = pltr.option_chain(expiry)

    expiry_calls = chain.calls.copy()
    expiry_puts = chain.puts.copy()

    expiry_calls["expiration"] = expiry
    expiry_puts["expiration"] = expiry

    expiry_calls.to_csv(
        data_dir / f"PLTR_calls_{expiry}.csv",
        index=False
    )

    expiry_puts.to_csv(
        data_dir / f"PLTR_puts_{expiry}.csv",
        index=False
    )

    print(expiry, len(expiry_calls), len(expiry_puts))

2026-11-20 57 57
2026-12-18 76 76
2027-01-15 73 73
2027-02-19 41 40

In [16]:
print(calls["lastTradeDate"].max())

2026-10-09 19:59:57+00:00

In [17]:
import json
from pathlib import Path

metadata_path = Path("../Data/PLTR_snapshot_metadata.json")

with open(metadata_path, "r") as f:
    metadata = json.load(f)

print(json.dumps(metadata, indent=2))

{
  "ticker": "PLTR",
  "expiration": "2027-01-15",
  "source": "Yahoo Finance via yfinance",
  "spot_reference": 198.72,
  "spot_reference_date": "2026-10-08",
  "option_quote_timestamp": "Unknown",
  "calls_count": 73,
  "puts_count": 73
}